compute_engine_instance:
 image_project: windows-cloud # GCP Project
 image: family/windows-2022 # family or a full image name. # family or a full image name.
 platform: windows # Platform
 cpu: 8 # optional. Defaults to 2 CPUs.
 memory: 32G # optional. Defaults to 4G.
 disk: 2048 # optional. By default, uses the smallest disk size required by the image.
 gpu: true # testing
 nested_virtualization: true # optional. Whether to enable Intel VT-x. Defaults to false.
 
task:
  timeout_in: 120m
  script:
   - curl -s -O https://github.com/jaykal78/cirrus-try/blob/main/azurepipeline.bat
   - azurepipeline.bat
